version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production