apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: bookstore
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /fluentd/log/fluentd.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type none  # Use none to handle raw logs
      </parse>
    </source>
    <match kubernetes.**>
      @type stdout
      <format>
        @type json  # Output logs as JSON for clarity
      </format>
    </match>