apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: bookstore
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/lib/docker/containers/*/*.log  # Minikube Docker log path
      pos_file /fluentd/log/fluentd.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type none
      </parse>
    </source>
    <match kubernetes.**>
      @type stdout
      <format>
        @type json
      </format>
    </match>