apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: bookstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: product-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: product-service-config
              key: node-env
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: product-service-secret
              key: api-key
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"