apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: bookstore
spec:
  selector:
    app: product-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: ClusterIP