apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: bookstore
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'user-service'
      static_configs:
      - targets: ['user-service:80']
    - job_name: 'product-service'
      static_configs:
      - targets: ['product-service:80']